### ISSUE TITLE
Address invalid kafka messages

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/donor-submission-aggregator#113] opened 2020-12-10 17:56 UTC
The aggregator got stuck on consuming incorrectly formatted messages i.e. missing studyId or programId,

When consuming an invalid message, it's throwing an error and does nothing so the event is never marked as processed, causing the aggregator to stall.

In the event that an invalid message is passed to the aggregator:

 log invalid messages out to slack, indicating the topic, partition and offset of the event,
 pass invalid messages to dlq. Example implementation: https://github.com/icgc-argo/files-service/blob/master/src/kafka.ts
 Have the aggregator move on to the next message

In the event that an invalid message is passed to the aggregator:
- [ ] log invalid messages out to slack, indicating the topic, partition and offset of the event, 
- [ ] Have the aggregator move on to the next message

FOLLOWUP FOR NEXT TICKET 
pass invalid messages to dlq.  Example implementation: https://github.com/icgc-argo/files-service/blob/master/src/kafka.ts

**Comment by hlminh2000** [comment] 2020-12-10 18:04
The problem isn't that it's enqueueing invalid messages (because it's not), but that it's throwing an error and does nothing so the event is never marked as processed. 

What we can do instead is log this out to slack, indicating the topic, partition and offset of the event, then move on.

**Comment by rosibaj** [comment] 2021-01-14 14:52
@Buwujiu I need a version label on this ticket before we can release it.

**Closed** 2021-01-15 20:49 UTC
Labels: SP:1, Scope Change, v1.13.0
